name: MetaQuest Automation

on:
  pull_request:
    branches:
      - main

jobs:
  run_metaquest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Install metaquest
      run: |
        pip install .

    - name: Download and setup Mastiff
      run: |
        curl -o mastiff -L https://github.com/sourmash-bio/mastiff/releases/latest/download/mastiff-client-x86_64-unknown-linux-musl
        chmod +x mastiff
        mkdir -p $HOME/.local/bin
        cp mastiff $HOME/.local/bin/mastiff
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        mastiff --version

    - name: Download Fasta from NCBI
      run: |
        metaquest download_test_genome

    - name: Run Mastiff
      run: |
        metaquest mastiff --genomes-folder genomes --matches-folder matches

    - name: parse_containment
      run: metaquest parse_containment --matches_folder matches --parsed_containment_file parsed_containment.txt --summary_containment_file summary_containment.txt

    - name: Plot containment
      run: metaquest plot_containment --file_path parsed_containment.txt --colors black --save_format png --threshold 0.05 --plot_type rank

    - name: Download Metadata
      run: metaquest download_metadata --email andreas.sjodin@gmail.com --matches_folder matches --metadata_folder metadata --threshold 0.95

    - name: Parse Metadata
      run: metaquest parse_metadata --metadata-folder metadata --metadata-table-file parsed_metadata.txt

    - name: Calculate metadata Count
      run: metaquest genome_count --summary-file parsed_containment.txt --metadata-file parsed_metadata.txt --metadata-column Sample_Scientific_Name --threshold 0.95  --output-file counts_Sample_Scientific_Name.txt

    - name: Plot metadata counts
      run: metaquest plot_metadata_counts --file_path counts_Sample_Scientific_Name.txt --plot_type bar --save_format png --colors black

    - name: Single Sample
      run: metaquest single_sample --summary-file parsed_containment.txt --metadata-file parsed_metadata.txt --summary-column GCF_000008985.1 --metadata-column  Sample_Scientific_Name  --threshold 0.95
