name: MetaQuest Automation

on:
  pull_request:
    branches:
      - main

jobs:
  run_metaquest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up Mamba and Install Dependencies
      run: |
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        ./bin/micromamba shell init -s bash -p ~/micromamba
        source ~/micromamba/bin/activate
        micromamba create -y -n mq-env
        micromamba activate mq-env
        mamba install --file requirements.txt

    - name: Install metaquest
      run: |
        pip install .

    - name: Download and setup Mastiff
      run: |
        curl -o mastiff -L https://github.com/sourmash-bio/mastiff/releases/latest/download/mastiff-client-x86_64-unknown-linux-musl
        chmod +x mastiff
        mkdir -p $HOME/.local/bin
        cp mastiff $HOME/.local/bin/mastiff
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        mastiff --version

    - name: Download Fasta from NCBI
      run: |
        metaquest  download-test-genome

    - name: Run Mastiff
      run: |
        metaquest mastiff --genomes-folder genomes --matches-folder matches

    - name: Summarize
      run: metaquest summarize --matches-folder matches --summary-file summary.txt --containment-file containment.txt

    - name: Download Metadata
      run: metaquest download-metadata --email andreas.sjodin@gmail.com --matches_folder matches --metadata_folder metadata --threshold 0.95

    - name: Parse Metadata
      run: metaquest parse-metadata --metadata-folder metadata --metadata-table-file parsed_metadata.txt

    - name: Genome Count
      run: metaquest genome_count --summary-file summary.txt --metadata-file parsed_metadata.txt --metadata-column Sample_Scientific_Name --threshold 0.95  --output-file genome_counts.txt

    - name: Single Sample
      run: metaquest single_sample --summary-file summary.txt --metadata-file parsed_metadata.txt --summary-column GCF_000008985.1 --metadata-column  Sample_Scientific_Name  --threshold 0.95
